/*
 * Copyright (C) 2016 fabian
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package GUI;

import static java.awt.event.KeyEvent.VK_ENTER;
import logic.IniHandler;
import logic.LangHandler;

/**
 *
 * @author fabian
 */
public class SettingsWindow extends javax.swing.JFrame {
    private final IniHandler ini;
    /**
     * Creates new form SettingsWindow
     */
    public SettingsWindow() {
        ini = IniHandler.getIni();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ydlPosLabel = new javax.swing.JLabel();
        ffmpegPosLabel = new javax.swing.JLabel();
        defDwnLabel = new javax.swing.JLabel();
        ydlPosTxtFld = new javax.swing.JTextField();
        ffmpegPosTxtFld = new javax.swing.JTextField();
        defDwnTxtFld = new javax.swing.JTextField();
        ydlFlChsrBtn = new javax.swing.JButton();
        ffmpegFlChsrBtn = new javax.swing.JButton();
        defDwnChsrBtn = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        saveWarning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(LangHandler.getValue("settings.window.title"));

        ydlPosLabel.setText("youtube-dl Position");

        ffmpegPosLabel.setText("ffmpeg Position");

        defDwnLabel.setText("default Download");

        ydlPosTxtFld.setText(ini.getProperty("youtube-dl.path.prefix"));
        ydlPosTxtFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ydlPosTxtFldKeyPressed(evt);
            }
        });

        ffmpegPosTxtFld.setText(ini.getProperty("ffmpeg.path.prefix"));
        ffmpegPosTxtFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ffmpegPosTxtFldKeyPressed(evt);
            }
        });

        defDwnTxtFld.setText(ini.getProperty("default-download.path"));
        defDwnTxtFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                defDwnTxtFldKeyPressed(evt);
            }
        });

        ydlFlChsrBtn.setText("...");
        ydlFlChsrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ydlFlChsrBtnActionPerformed(evt);
            }
        });

        ffmpegFlChsrBtn.setText("...");
        ffmpegFlChsrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ffmpegFlChsrBtnActionPerformed(evt);
            }
        });

        defDwnChsrBtn.setText("...");
        defDwnChsrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defDwnChsrBtnActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        saveWarning.setForeground(new java.awt.Color(255, 0, 0));
        saveWarning.setText("            ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(ydlPosLabel)
                .addGap(12, 12, 12)
                .addComponent(ydlPosTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(ydlFlChsrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(ffmpegPosLabel)
                .addGap(12, 12, 12)
                .addComponent(ffmpegPosTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(ffmpegFlChsrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(defDwnLabel)
                .addGap(12, 12, 12)
                .addComponent(defDwnTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(defDwnChsrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveWarning))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ydlPosLabel))
                    .addComponent(ydlPosTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(ydlFlChsrBtn)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ffmpegPosLabel))
                    .addComponent(ffmpegPosTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(ffmpegFlChsrBtn)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(defDwnLabel))
                    .addComponent(defDwnTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(defDwnChsrBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void defDwnTxtFldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_defDwnTxtFldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == VK_ENTER){
            ini.setProperty("default-download.path", defDwnTxtFld.getText());
            defDwnTxtFld.setText(ini.getProperty("default-download.path"));
            MainWindowHandler.getMWI().updateDefDwnDst(ini.getProperty("default-download.path"));
        }
    }//GEN-LAST:event_defDwnTxtFldKeyPressed

    private void ydlFlChsrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ydlFlChsrBtnActionPerformed
        // TODO add your handling code here:
        YdlFileChooser chooser = CustomDialogs.ydlLocation(this);
        if(chooser.showDiag()!=0){
            String path = chooser.getPath();
            ydlPosTxtFld.setText(path);
            ini.setProperty("youtube-dl.path.prefix", path);
        }
    }//GEN-LAST:event_ydlFlChsrBtnActionPerformed

    private void ffmpegFlChsrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ffmpegFlChsrBtnActionPerformed
        // TODO add your handling code here:
        YdlFileChooser chooser = CustomDialogs.ffmpegLocation(this);
        if(chooser.showDiag()!=0){
            String path = chooser.getPath();
            ffmpegPosTxtFld.setText(path);
            ini.setProperty("ffmpeg.path.prefix", path);
        }
    }//GEN-LAST:event_ffmpegFlChsrBtnActionPerformed

    private void defDwnChsrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defDwnChsrBtnActionPerformed
        // TODO add your handling code here:
        YdlFileChooser chooser = new YdlFileChooser(this);
        if(chooser.showDiag()!=0){
            String path = chooser.getPath();
            defDwnTxtFld.setText(path);
            ini.setProperty("default-download.path", path);
            MainWindowHandler.getMWI().updateDefDwnDst(ini.getProperty("default-download.path"));
        }
    }//GEN-LAST:event_defDwnChsrBtnActionPerformed

    private void ydlPosTxtFldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ydlPosTxtFldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == VK_ENTER){
            ini.setProperty("youtube-dl.path.prefix", defDwnTxtFld.getText());
            defDwnTxtFld.setText(ini.getProperty("youtube-dl.path.prefix"));
        }
    }//GEN-LAST:event_ydlPosTxtFldKeyPressed

    private void ffmpegPosTxtFldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ffmpegPosTxtFldKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == VK_ENTER){
            ini.setProperty("ffmpeg.path.prefix", defDwnTxtFld.getText());
            defDwnTxtFld.setText(ini.getProperty("ffmpeg.path.prefix"));
        }
    }//GEN-LAST:event_ffmpegPosTxtFldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SettingsWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton defDwnChsrBtn;
    private javax.swing.JLabel defDwnLabel;
    private javax.swing.JTextField defDwnTxtFld;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton ffmpegFlChsrBtn;
    private javax.swing.JLabel ffmpegPosLabel;
    private javax.swing.JTextField ffmpegPosTxtFld;
    private javax.swing.JLabel saveWarning;
    private javax.swing.JButton ydlFlChsrBtn;
    private javax.swing.JLabel ydlPosLabel;
    private javax.swing.JTextField ydlPosTxtFld;
    // End of variables declaration//GEN-END:variables
}
